"""docreg — Notion-database catalogue of produced document instances and versions.

Each *major build* publishes a NEW Google Doc instance (so prior reviewers keep their Doc and
its comments intact); this connector records one row per instance — artifact, version, Doc URL,
the git commit it was rendered from, a content hash, date, and status (current | superseded).
`gdoc push` writes here automatically when a registry is bound (`notion.docs_registry` in
connections.yaml): a fresh Doc (first push or `gdoc push --new`) is a new instance; a plain
push refreshes the current row. Reuses the `notion` connector's REST helpers — no new creds.

Verbs
-----
  init  [--parent PAGE] [--title T]   create the Notion DB (schema below) + bind it in connections.yaml
  log   --artifact A [--version V] [--doc-id I] [--doc-url U] [--git-sha S] [--new]
                                      append/update a row (gdoc push calls this for you)
  list  [--artifact A]                show recorded instances (current marked *)
  pull                                rewrite the optional local projection (project_to)
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from .. import config
from . import notion

STATUSES = ["current", "superseded"]
BEGIN = "<!-- BEGIN DOC REGISTRY (generated by `bizconnect docreg pull`) -->"
END = "<!-- END DOC REGISTRY -->"


def _today():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _opt(argv, name, default=None):
    if name in argv:
        i = argv.index(name)
        if i + 1 < len(argv):
            return argv[i + 1]
    return default


def _repo():
    data, path = config.require_connections()
    return data, path, path.parent


def _abs(root, p):
    pp = Path(p)
    return pp if pp.is_absolute() else (root / p)


def _rich(s, limit=1900):
    s = s or ""
    return [{"type": "text", "text": {"content": s[i:i + limit]}} for i in range(0, len(s), limit)]


def _db(data):
    rd = config.get_path(data, "notion.docs_registry") or {}
    return rd if isinstance(rd, dict) else {}


def _db_id(data):
    did = _db(data).get("database_id")
    if not did:
        sys.exit("no docs registry bound. Run `bizconnect docreg init` first.")
    return did


def _set_db(data, path, fields):
    from ruamel.yaml.comments import CommentedMap
    n = data.get("notion")
    if not isinstance(n, dict):
        n = CommentedMap()
        data["notion"] = n
    rd = n.get("docs_registry")
    if not isinstance(rd, CommentedMap):
        merged = CommentedMap()
        if isinstance(rd, dict):
            for k, v in rd.items():
                merged[k] = v
        rd = merged
        n["docs_registry"] = rd
    for k, v in fields.items():
        rd[k] = v
    config.save_connections(data, path)


def _select(values):
    return [{"name": v} for v in values]


PROPS = {
    "Name": {"title": {}},
    "Artifact": {"rich_text": {}},
    "Version": {"rich_text": {}},
    "Status": {"select": {"options": _select(STATUSES)}},
    "DocURL": {"url": {}},
    "DocId": {"rich_text": {}},
    "GitSHA": {"rich_text": {}},
    "ContentSHA": {"rich_text": {}},
    "PushedAt": {"date": {}},
    "PushedBy": {"rich_text": {}},
    "Notes": {"rich_text": {}},
}


def _ptext(rich):
    return "".join(r.get("plain_text", "") for r in (rich or []))


def _row_get(page, name):
    p = page.get("properties", {}).get(name, {})
    t = p.get("type")
    if t == "title":
        return _ptext(p.get("title"))
    if t == "rich_text":
        return _ptext(p.get("rich_text"))
    if t == "select":
        return (p.get("select") or {}).get("name", "")
    if t == "date":
        return (p.get("date") or {}).get("start", "")
    if t == "url":
        return p.get("url") or ""
    return ""


def _query(data, filt=None):
    did = _db_id(data)
    out, cursor = [], None
    while True:
        b = {"page_size": 100}
        if filt:
            b["filter"] = filt
        if cursor:
            b["start_cursor"] = cursor
        status, resp = notion.api("POST", "/databases/%s/query" % did, body=b)
        notion._die(status, resp, "query docs registry")
        out.extend(resp.get("results", []))
        if not resp.get("has_more"):
            break
        cursor = resp.get("next_cursor")
    return out


def _props(artifact, version, doc_id, doc_url, status, git_sha, content_sha, pushed_by, notes):
    p = {"Name": {"title": _rich("%s %s" % (artifact, version or ""))},
         "Artifact": {"rich_text": _rich(artifact)},
         "Status": {"select": {"name": status}},
         "PushedAt": {"date": {"start": _today()}}}
    if version:
        p["Version"] = {"rich_text": _rich(version)}
    if doc_url:
        p["DocURL"] = {"url": doc_url}
    if doc_id:
        p["DocId"] = {"rich_text": _rich(doc_id)}
    if git_sha:
        p["GitSHA"] = {"rich_text": _rich(git_sha)}
    if content_sha:
        p["ContentSHA"] = {"rich_text": _rich(content_sha)}
    if pushed_by:
        p["PushedBy"] = {"rich_text": _rich(pushed_by)}
    if notes:
        p["Notes"] = {"rich_text": _rich(notes)}
    return p


def _page_to_row(pg):
    return {"artifact": _row_get(pg, "Artifact"), "version": _row_get(pg, "Version"),
            "status": _row_get(pg, "Status"), "doc_url": _row_get(pg, "DocURL"),
            "doc_id": _row_get(pg, "DocId"), "git_sha": _row_get(pg, "GitSHA"),
            "content_sha": _row_get(pg, "ContentSHA"), "pushed_at": _row_get(pg, "PushedAt")}


def log_instance(data, root, *, artifact, doc_id="", doc_url="", version=None,
                 content_sha="", git_sha="", pushed_by="", notes="", new=False):
    """Append/update a registry row. No-op (returns None) if no registry is bound. A new
    instance supersedes prior current rows for the same artifact; otherwise the current row
    is refreshed. Called by `gdoc push` and by `docreg log`."""
    if not _db(data).get("database_id"):
        return None
    rows = _query(data, filt={"property": "Artifact", "rich_text": {"equals": artifact}})
    current = [r for r in rows if _row_get(r, "Status") == "current"]
    if new or not current:
        for r in current:
            notion.api("PATCH", "/pages/%s" % r["id"],
                       body={"properties": {"Status": {"select": {"name": "superseded"}}}})
        ver = version or "v%d" % (len(rows) + 1)
        st, resp = notion.api("POST", "/pages", body={
            "parent": {"database_id": _db_id(data)},
            "properties": _props(artifact, ver, doc_id, doc_url, "current",
                                 git_sha, content_sha, pushed_by, notes)})
        notion._die(st, resp, "log doc instance")
        return "new instance %s" % ver
    r = current[0]
    ver = version or _row_get(r, "Version")
    st, resp = notion.api("PATCH", "/pages/%s" % r["id"], body={
        "properties": _props(artifact, ver, doc_id, doc_url, "current",
                             git_sha, content_sha, pushed_by, notes)})
    notion._die(st, resp, "update doc instance")
    return "refreshed %s" % (ver or artifact)


# --- verbs --------------------------------------------------------------------
def cmd_init(argv):
    data, conn_path, root = _repo()
    rd = _db(data)
    if rd.get("database_id"):
        print("docs registry already bound: %s" % (rd.get("url") or rd["database_id"]))
        return
    parent = (_opt(argv, "--parent") or rd.get("parent") or config.get_path(data, "notion.notes_page"))
    if not parent:
        sys.exit("need a parent page: pass --parent <page-url/id> or set notion.notes_page.")
    pid = notion.norm_id(parent)
    title = _opt(argv, "--title", "Document registry — produced versions")
    st, resp = notion.api("POST", "/databases", body={
        "parent": {"type": "page_id", "page_id": pid}, "title": _rich(title), "properties": PROPS})
    notion._die(st, resp, "create docs registry")
    _set_db(data, conn_path, {"database_id": resp["id"], "url": resp.get("url") or ""})
    print("created docs registry:\n  %s" % (resp.get("url") or resp["id"]))
    print("  (binding written to %s under notion.docs_registry)" % conn_path.name)


def cmd_log(argv):
    data, conn_path, root = _repo()
    artifact = _opt(argv, "--artifact")
    if not artifact:
        sys.exit("log needs --artifact <repo-relative-file>")
    msg = log_instance(data, root, artifact=artifact, version=_opt(argv, "--version"),
                       doc_id=_opt(argv, "--doc-id", ""), doc_url=_opt(argv, "--doc-url", ""),
                       git_sha=_opt(argv, "--git-sha", ""), content_sha=_opt(argv, "--content-sha", ""),
                       pushed_by=_opt(argv, "--by", ""), notes=_opt(argv, "--notes", ""),
                       new=("--new" in argv))
    print("docreg: %s" % (msg or "no registry bound (notion.docs_registry) — nothing logged"))


def cmd_list(argv):
    data, conn_path, root = _repo()
    if not _db(data).get("database_id"):
        print("no docs registry bound. Run `bizconnect docreg init`.")
        return
    art = _opt(argv, "--artifact")
    filt = {"property": "Artifact", "rich_text": {"equals": art}} if art else None
    rows = sorted((_page_to_row(p) for p in _query(data, filt)),
                  key=lambda r: (r["artifact"], r["version"]))
    if not rows:
        print("(no instances recorded)")
        return
    for r in rows:
        mark = "*" if r["status"] == "current" else " "
        print("%s %-28s %-8s %-10s %-9s %s" % (
            mark, r["artifact"], r["version"], r["pushed_at"], r["git_sha"], r["doc_url"]))


def cmd_pull(argv):
    data, conn_path, root = _repo()
    proj = _db(data).get("project_to")
    if not proj:
        sys.exit("notion.docs_registry.project_to not set in connections.yaml")
    rows = sorted((_page_to_row(p) for p in _query(data)),
                  key=lambda r: (r["artifact"], r["version"]))
    lines = ["| artifact | version | status | date | git | doc |", "|---|---|---|---|---|---|"]
    for r in rows:
        lines.append("| %s | %s | %s | %s | %s | %s |" % (
            r["artifact"], r["version"], r["status"], r["pushed_at"], r["git_sha"], r["doc_url"]))
    block = "%s\n%s\n%s" % (BEGIN, "\n".join(lines), END)
    p = _abs(root, proj)
    if p.exists():
        txt = p.read_text(encoding="utf-8")
        if BEGIN in txt and END in txt:
            txt = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _m: block, txt, flags=re.S)
        else:
            txt = txt.rstrip() + "\n\n" + block + "\n"
    else:
        p.parent.mkdir(parents=True, exist_ok=True)
        txt = "# Document registry (projection)\n\n" + block + "\n"
    p.write_text(txt, encoding="utf-8")
    print("docreg pull: wrote %d instance(s) -> %s" % (len(rows), proj))


VERBS = {"init": cmd_init, "log": cmd_log, "list": cmd_list, "pull": cmd_pull}


def run(argv):
    if not argv or argv[0] in ("-h", "--help", "help"):
        print(__doc__)
        return 0
    verb, rest = argv[0], argv[1:]
    fn = VERBS.get(verb)
    if not fn:
        sys.exit("unknown docreg verb %r. One of: %s" % (verb, ", ".join(VERBS)))
    fn(rest)
    return 0
