"""register — a Notion-database-backed open-points register for review feedback.

The register is the *stateful spine* of the feedback roundtrip (see the `doc-pipeline` and
`feedback-ingest` skills). Reviewers mark up the rendered document in Google Docs; the
`compose` `assimilate` stage lifts each comment into an open point with references and
triages it by disposition; this connector PERSISTS those points as rows in a Notion
database, renders a local read-only projection the pipeline reads, and journals every cycle.

Content-free: the Notion database id + the projection/journal paths are bound per-repo in
connections.yaml under `notion.register_db`. Reuses the `notion` connector's REST helpers
(auth, blocks) — no new credentials.

Field ownership (mirrors compose's human-owned-vs-proposed rule, at row-field level):
  ingest OWNS  ISS, Disposition, Questions, Layer, Targets, Marker, DocLink, Author,
               SourceCommentId, and the Input/Interpretation prose;
  humans OWN   Status, Owner, Agreed steps, Commentary additions.
`upsert` never overwrites human-owned fields on an existing row — it fills machine fields
and APPENDS to the History block. Always `pull` before `upsert` and merge, don't clobber.

Verbs
-----
  init    [--parent PAGE] [--title T]   create the Notion DB (schema below) + bind it in connections.yaml
  pull                                  query rows -> rewrite the local projection (project_to)
  upsert  <deltas.json|.md>             create/update rows (dedupe by source comment-id); append History
  open    [--question Qnn]              print the OPEN points slice (what feeds compose's {{OPEN_POINTS}})
  status                                counts by status/disposition; open-gated count; reachability
  resolve <ISS> [--note T]              mark a point resolved + append History
  journal                               show the per-cycle ingestion journal
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from .. import config
from . import notion

# --- vocab (kept in sync with response/register/open-points.md) ---------------
STATUSES = ["open", "triaged", "in-discussion", "agreed", "actioned", "rebuilt",
            "resolved", "parked", "superseded", "wont-do"]
DISPOSITIONS = ["finesse", "tonal", "rethink", "research", "discussion"]
LAYERS = ["answer", "spec", "house-position", "prompt"]
GATED = {"rethink", "research", "discussion"}
OPEN_STATES = {"open", "triaged", "in-discussion", "agreed", "actioned"}
QUESTION_OPTS = ["front-matter"] + ["Q%02d" % i for i in range(1, 40)]

BEGIN = "<!-- BEGIN REGISTER (generated by `bizconnect register pull`) -->"
END = "<!-- END REGISTER -->"


# --- small helpers ------------------------------------------------------------
def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _today():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _opt(argv, name, default=None):
    if name in argv:
        i = argv.index(name)
        if i + 1 < len(argv):
            return argv[i + 1]
    return default


def _positional(argv, value_flags=()):
    skip = set()
    for vf in value_flags:
        if vf in argv:
            skip.add(argv.index(vf) + 1)
    for i, a in enumerate(argv):
        if i in skip or a.startswith("-"):
            continue
        return a
    return None


def _repo():
    data, path = config.require_connections()
    return data, path, path.parent


def _abs(root, p):
    pp = Path(p)
    return pp if pp.is_absolute() else (root / p)


def _rich(s, limit=1900):
    """Rich-text array, chunked under Notion's 2000-char-per-node cap."""
    s = s or ""
    return [{"type": "text", "text": {"content": s[i:i + limit]}} for i in range(0, len(s), limit)]


def _db(data):
    # Scope to the active deliverable (deliverables.<slug>.notion.register_db) when running
    # inside one; falls back to top-level notion.register_db for single-deliverable repos.
    rd = config.scoped(data, "notion.register_db") or {}
    return rd if isinstance(rd, dict) else {}


def _db_id(data):
    did = _db(data).get("database_id")
    if not did:
        sys.exit("no Notion register bound. Run `bizconnect register init` first "
                 "(or set notion.register_db.database_id in connections.yaml).")
    return did


def _set_db(data, path, fields):
    from ruamel.yaml.comments import CommentedMap
    n = data.get("notion")
    if not isinstance(n, dict):
        n = CommentedMap()
        data["notion"] = n
    rd = n.get("register_db")
    if not isinstance(rd, CommentedMap):
        merged = CommentedMap()
        if isinstance(rd, dict):
            for k, v in rd.items():
                merged[k] = v
        rd = merged
        n["register_db"] = rd
    for k, v in fields.items():
        rd[k] = v
    config.save_connections(data, path)


# --- Notion property <-> row dict --------------------------------------------
def _select_opts(values):
    return [{"name": v} for v in values]


PROPS = {
    "Name": {"title": {}},
    "ISS": {"rich_text": {}},
    "Status": {"select": {"options": _select_opts(STATUSES)}},
    "Disposition": {"select": {"options": _select_opts(DISPOSITIONS)}},
    "Layer": {"select": {"options": _select_opts(LAYERS)}},
    "Questions": {"multi_select": {"options": _select_opts(QUESTION_OPTS)}},
    "Targets": {"rich_text": {}},
    "Marker": {"rich_text": {}},
    "Related": {"rich_text": {}},
    "Owner": {"rich_text": {}},
    "Raised": {"date": {}},
    "Author": {"rich_text": {}},
    "SourceCommentId": {"rich_text": {}},
    "DocLink": {"url": {}},
    # HUMAN-OWNED. The reviewer's actionable resolution for this point. Projected into the local
    # open-points file and thus into the next draft's {{OPEN_POINTS}}, so a Notion edit here is
    # what flows the decision back into the document on the next build. (Discussion stays in the
    # page body; this is the one-line instruction the generator consumes.)
    "AgreedStep": {"rich_text": {}},
}


def _ptext(rich):
    return "".join(r.get("plain_text", "") for r in (rich or []))


def _row_get(page, name):
    p = page.get("properties", {}).get(name, {})
    t = p.get("type")
    if t == "title":
        return _ptext(p.get("title"))
    if t == "rich_text":
        return _ptext(p.get("rich_text"))
    if t == "select":
        return (p.get("select") or {}).get("name", "")
    if t == "multi_select":
        return [o["name"] for o in p.get("multi_select", [])]
    if t == "date":
        return (p.get("date") or {}).get("start", "")
    if t == "url":
        return p.get("url") or ""
    return ""


def _prop_set(row, machine_only=False):
    """Build a Notion `properties` body from a delta dict. With machine_only, omit the
    human-owned Status/Owner so an update never clobbers a human decision."""
    props = {"Name": {"title": _rich("%s · %s" % (row.get("iss", ""), row.get("title", "")))}}
    if row.get("iss"):
        props["ISS"] = {"rich_text": _rich(row["iss"])}
    if row.get("disposition"):
        props["Disposition"] = {"select": {"name": row["disposition"]}}
    if row.get("layer"):
        props["Layer"] = {"select": {"name": row["layer"]}}
    if row.get("questions"):
        props["Questions"] = {"multi_select": [{"name": q} for q in row["questions"]]}
    for key, prop in [("targets", "Targets"), ("marker", "Marker"), ("related", "Related"),
                      ("author", "Author"), ("source_comment_id", "SourceCommentId")]:
        v = row.get(key)
        if isinstance(v, list):
            v = ", ".join(v)
        if v:
            props[prop] = {"rich_text": _rich(v)}
    if row.get("raised"):
        props["Raised"] = {"date": {"start": row["raised"]}}
    if row.get("doc_link"):
        props["DocLink"] = {"url": row["doc_link"]}
    if not machine_only:
        if row.get("status"):
            props["Status"] = {"select": {"name": row["status"]}}
        if row.get("owner"):
            props["Owner"] = {"rich_text": _rich(row["owner"])}
        if row.get("agreed_step"):
            props["AgreedStep"] = {"rich_text": _rich(row["agreed_step"])}
    return props


def _body_blocks(row):
    blocks = []
    for label, key in [("Input", "input"), ("Interpretation", "interpretation"),
                       ("Commentary", "commentary"), ("Recommendation", "recommendation"),
                       ("Agreed steps", "agreed_steps"), ("History", "history_append")]:
        v = row.get(key)
        if v:
            blocks.append({"type": "heading_3", "heading_3": {"rich_text": _rich(label)}})
            blocks.append({"type": "paragraph", "paragraph": {"rich_text": _rich(v)}})
    return blocks


def _page_to_row(pg):
    name = _row_get(pg, "Name")
    return {
        "iss": _row_get(pg, "ISS") or (name.split("·")[0].strip()),
        "title": name.split("·", 1)[-1].strip() if "·" in name else name,
        "status": _row_get(pg, "Status"), "disposition": _row_get(pg, "Disposition"),
        "layer": _row_get(pg, "Layer"), "questions": _row_get(pg, "Questions"),
        "targets": _row_get(pg, "Targets"), "marker": _row_get(pg, "Marker"),
        "related": _row_get(pg, "Related"), "owner": _row_get(pg, "Owner"),
        "raised": _row_get(pg, "Raised"), "author": _row_get(pg, "Author"),
        "source_comment_id": _row_get(pg, "SourceCommentId"), "doc_link": _row_get(pg, "DocLink"),
        "agreed_step": _row_get(pg, "AgreedStep"),
    }


# --- Notion DB query ----------------------------------------------------------
def _query(data, filt=None):
    did = _db_id(data)
    out, cursor = [], None
    while True:
        b = {"page_size": 100}
        if filt:
            b["filter"] = filt
        if cursor:
            b["start_cursor"] = cursor
        status, resp = notion.api("POST", "/databases/%s/query" % did, body=b)
        notion._die(status, resp, "query register")
        out.extend(resp.get("results", []))
        if not resp.get("has_more"):
            break
        cursor = resp.get("next_cursor")
    return out


def _ensure_props(data):
    """Add any PROPS missing from the live register DB (e.g. AgreedStep on a register created
    before that field existed). Idempotent + cheap, so the schema can evolve without a manual
    migration. Never removes or rewrites existing properties."""
    did = _db(data).get("database_id")
    if not did:
        return
    try:
        st, resp = notion.api("GET", "/databases/%s" % did)
        if st >= 300:
            return
        have = set((resp or {}).get("properties", {}).keys())
        missing = {k: v for k, v in PROPS.items() if k not in have and k != "Name"}
        if missing:
            notion.api("PATCH", "/databases/%s" % did, body={"properties": missing})
    except Exception:
        pass


# --- projection (Notion -> local read-only Markdown) --------------------------
def _render_entry(r):
    L = ["### %s · %s" % (r["iss"], r["title"]),
         "- status:       %s" % (r["status"] or "?"),
         "- disposition:  %s" % (r["disposition"] or "?")]
    raised = " · ".join(x for x in [
        r.get("raised"), r.get("author"),
        ("src:" + r["source_comment_id"]) if r.get("source_comment_id") else ""] if x)
    if raised:
        L.append("- raised:       %s" % raised)
    if r.get("questions"):
        qs = r["questions"] if isinstance(r["questions"], list) else [r["questions"]]
        L.append("- questions:    [%s]" % ", ".join(qs))
    for label, key in [("layer", "layer"), ("targets", "targets"), ("marker", "marker"),
                       ("related", "related"), ("owner", "owner"), ("doc", "doc_link")]:
        if r.get(key):
            L.append("- %-11s %s" % (label + ":", r[key]))
    if r.get("agreed_step"):                       # the reviewer's decision — the draft applies it
        L.append("- AGREED STEP (apply this in the draft): %s" % r["agreed_step"])
    L.append("")
    return "\n".join(L)


def _write_projection(data, root):
    proj = _db(data).get("project_to")
    if not proj:
        return None
    rows = [_page_to_row(pg) for pg in _query(data)]
    rows.sort(key=lambda r: r.get("iss", ""))
    body = "\n".join(_render_entry(r) for r in rows) if rows else "_None._"
    block = "%s\n_Generated by `bizconnect register pull` — do not hand-edit (%d point(s))._\n\n%s\n%s" % (
        BEGIN, len(rows), body, END)
    p = _abs(root, proj)
    if p.exists():
        txt = p.read_text(encoding="utf-8")
        if BEGIN in txt and END in txt:
            txt = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _m: block, txt, flags=re.S)
        else:
            txt = txt.rstrip() + "\n\n" + block + "\n"
    else:
        p.parent.mkdir(parents=True, exist_ok=True)
        txt = "# Open points (projection)\n\n" + block + "\n"
    p.write_text(txt, encoding="utf-8")
    return len(rows)


def _split_entries(text):
    if BEGIN in text and END in text:
        text = text.split(BEGIN, 1)[1].split(END, 1)[0]
    parts = re.split(r"(?m)^### ", text)
    return ["### " + p.strip() for p in parts[1:] if p.strip()]


# --- deltas (assimilate output -> rows) --------------------------------------
def _load_deltas(path):
    txt = Path(path).read_text(encoding="utf-8")
    if str(path).endswith(".json"):
        data = json.loads(txt)
    else:
        m = re.search(r"```json\s*(.*?)```", txt, re.S)
        if not m:
            sys.exit("no ```json deltas block found in %s" % path)
        data = json.loads(m.group(1))
    if isinstance(data, dict):
        data = data.get("deltas") or data.get("rows") or []
    return data


# --- journal ------------------------------------------------------------------
def _journal_append(root, data, record):
    jdir = _db(data).get("journal")
    if not jdir:
        return
    d = _abs(root, jdir)
    d.mkdir(parents=True, exist_ok=True)
    rec = {"at": _now(), **record}
    with open(d / "index.jsonl", "a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec) + "\n")


# --- verbs --------------------------------------------------------------------
def cmd_init(argv):
    data, conn_path, root = _repo()
    rd = _db(data)
    if rd.get("database_id"):
        print("register already bound: %s" % (rd.get("url") or rd["database_id"]))
        return
    parent = (_opt(argv, "--parent") or rd.get("parent")
              or config.get_path(data, "notion.notes_page"))
    if not parent:
        sys.exit("need a parent page: pass --parent <page-url/id> or set notion.notes_page "
                 "(or notion.register_db.parent) in connections.yaml.")
    pid = notion.norm_id(parent)
    title = _opt(argv, "--title", "Open points — review register")
    body = {"parent": {"type": "page_id", "page_id": pid},
            "title": _rich(title), "properties": PROPS}
    status, resp = notion.api("POST", "/databases", body=body)
    notion._die(status, resp, "create register database")
    did, url = resp["id"], resp.get("url") or ""
    _set_db(data, conn_path, {"database_id": did, "url": url})
    print("created register database:\n  %s" % (url or did))
    print("  (binding written to %s under notion.register_db)" % conn_path.name)


def cmd_pull(argv):
    data, conn_path, root = _repo()
    _ensure_props(data)
    n = _write_projection(data, root)
    if n is None:
        sys.exit("notion.register_db.project_to not set in connections.yaml")
    print("register pull: wrote %d point(s) -> %s" % (n, _db(data).get("project_to")))
    _journal_append(root, data, {"op": "pull", "rows": n})


def _next_iss(pages):
    """Next free ISS-nnn, continuing the register's sequence (max existing + 1)."""
    nums = []
    for pg in pages:
        m = re.match(r"ISS-(\d+)", _row_get(pg, "ISS") or "")
        if m:
            nums.append(int(m.group(1)))
    return max(nums, default=0) + 1


def source_id_to_iss(data=None):
    """Map each row's SourceCommentId -> its ISS id (for callers that allocate ids via upsert
    and then need to learn which ISS each source point received — e.g. compose `harvest`)."""
    if data is None:
        data, _ = config.require_connections()
    out = {}
    for pg in _query(data):
        sid, iss = _row_get(pg, "SourceCommentId"), _row_get(pg, "ISS")
        if sid and iss:
            out[sid] = iss
    return out


def cmd_upsert(argv):
    data, conn_path, root = _repo()
    _ensure_props(data)
    f = _positional(argv)
    if not f:
        sys.exit("upsert needs <deltas.json|.md>")
    deltas = _load_deltas(str(_abs(root, f)))
    did = _db_id(data)
    pages = _query(data)
    existing = {}
    for pg in pages:
        # key each row by BOTH its source-id and its ISS, so a delta can match an existing row
        # by either (a re-harvested point carries its ISS forward as the stable identity).
        for k in (_row_get(pg, "SourceCommentId"), _row_get(pg, "ISS")):
            if k:
                existing[k] = pg
    seq = _next_iss(pages)
    created = updated = 0
    for row in deltas:
        keyv = row.get("source_comment_id") or row.get("iss")
        pg = existing.get(keyv)
        if pg:
            st, resp = notion.api("PATCH", "/pages/%s" % pg["id"],
                                  body={"properties": _prop_set(row, machine_only=True)})
            notion._die(st, resp, "update row %s" % keyv)
            if row.get("history_append"):
                notion.attach(pg["id"], [{"type": "paragraph", "paragraph": {
                    "rich_text": _rich("• %s — %s" % (_today(), row["history_append"]))}}])
            updated += 1
        else:
            if not row.get("iss"):          # allocate the next ISS for a brand-new point
                row["iss"] = "ISS-%03d" % seq
                seq += 1
            row.setdefault("status", "triaged")
            st, resp = notion.api("POST", "/pages", body={
                "parent": {"database_id": did},
                "properties": _prop_set(row), "children": _body_blocks(row)})
            notion._die(st, resp, "create row %s" % keyv)
            created += 1
    print("register upsert: %d created, %d updated" % (created, updated))
    _journal_append(root, data, {"op": "upsert", "created": created, "updated": updated, "source": f})
    if _db(data).get("project_to"):
        _write_projection(data, root)


def cmd_open(argv):
    data, conn_path, root = _repo()
    q = _opt(argv, "--question")
    proj = _db(data).get("project_to")
    p = _abs(root, proj) if proj else None
    text = p.read_text(encoding="utf-8") if p and p.exists() else ""
    out = []
    for e in _split_entries(text):
        ms = re.search(r"status:\s*([\w-]+)", e)
        if ms and ms.group(1) not in OPEN_STATES:
            continue
        if q:
            mq = re.search(r"questions:.*", e)
            if not (mq and re.search(r"\b%s\b" % re.escape(q), mq.group(0))):
                continue
        out.append(e)
    print("\n".join(out).strip() or ("(no open points%s)" % ((" for " + q) if q else "")))


def cmd_status(argv):
    data, conn_path, root = _repo()
    rd = _db(data)
    if not rd.get("database_id"):
        print("no register bound. Run `bizconnect register init`.")
        return
    from collections import Counter
    rows = [_page_to_row(pg) for pg in _query(data)]
    bys = Counter(r["status"] or "?" for r in rows)
    byd = Counter(r["disposition"] or "?" for r in rows)
    gated = sum(1 for r in rows if r["disposition"] in GATED and r["status"] in OPEN_STATES)
    print("register: %s" % (rd.get("url") or rd["database_id"]))
    print("  rows: %d" % len(rows))
    print("  by status:      " + (", ".join("%s=%d" % (k, v) for k, v in sorted(bys.items())) or "-"))
    print("  by disposition: " + (", ".join("%s=%d" % (k, v) for k, v in sorted(byd.items())) or "-"))
    print("  open & gated (need a human): %d" % gated)
    proj = rd.get("project_to")
    if proj:
        present = "present" if _abs(root, proj).exists() else "MISSING (run `register pull`)"
        print("  projection: %s — %s" % (proj, present))


def cmd_resolve(argv):
    data, conn_path, root = _repo()
    iss = _positional(argv, value_flags=("--note",))
    if not iss:
        sys.exit("resolve needs <ISS-id>")
    note = _opt(argv, "--note", "")
    pages = _query(data, filt={"property": "ISS", "rich_text": {"equals": iss}})
    if not pages:
        sys.exit("no register row with ISS %r" % iss)
    pg = pages[0]
    st, resp = notion.api("PATCH", "/pages/%s" % pg["id"],
                          body={"properties": {"Status": {"select": {"name": "resolved"}}}})
    notion._die(st, resp, "resolve %s" % iss)
    notion.attach(pg["id"], [{"type": "paragraph", "paragraph": {
        "rich_text": _rich("• %s — resolved%s" % (_today(), (": " + note) if note else ""))}}])
    print("resolved %s" % iss)
    _journal_append(root, data, {"op": "resolve", "iss": iss})
    if _db(data).get("project_to"):
        _write_projection(data, root)


def cmd_journal(argv):
    data, conn_path, root = _repo()
    jdir = _db(data).get("journal")
    if not jdir:
        sys.exit("notion.register_db.journal not set in connections.yaml")
    idx = _abs(root, jdir) / "index.jsonl"
    if not idx.exists():
        print("(journal empty)")
        return
    for line in idx.read_text(encoding="utf-8").splitlines():
        try:
            r = json.loads(line)
        except Exception:
            continue
        extra = {k: v for k, v in r.items() if k not in ("at", "op")}
        print("%s  %-8s %s" % (r.get("at", ""), r.get("op", ""), extra))


VERBS = {"init": cmd_init, "pull": cmd_pull, "upsert": cmd_upsert, "open": cmd_open,
         "status": cmd_status, "resolve": cmd_resolve, "journal": cmd_journal}


def run(argv):
    if not argv or argv[0] in ("-h", "--help", "help"):
        print(__doc__)
        return 0
    verb, rest = argv[0], argv[1:]
    fn = VERBS.get(verb)
    if not fn:
        sys.exit("unknown register verb %r. One of: %s" % (verb, ", ".join(VERBS)))
    fn(rest)
    return 0
